branches:
  only:
  - master
language: python
python:
- 2.7
env:
  global:
  - secure: AiPYTKfVUmIE/cXfd7CWLAj6uXbYBPHzklbLul/yt6BNZAe0CKdOehOAyRUlc0xc4F+GsB/IccUBC49jxvHBqxTuAJ8pYKFpESb37pCJB2R58IWNjr8QRCPz8W3NiNr3WsNs5nmH7eHzZ2rOvPJnV+V7DLDnhtXGcwSWmKL6s7U=


before_install:
- sudo apt-get install pandoc
- git submodule update --init --recursive
install:
- pip install -r requirements.txt --use-mirrors
script:
- fab build
after_success: bash deploy.sh
notifications:
  email:
    on_success: always
    on_failure: always
