branches:
  only:
  - master
language: python
python:
- 2.7
env:
  global:
  - secure: f6n8ZepQMx0d3czz1Jz6EJziIsjW88egLY3suZNDy1Zx0+LfzyYZ/js5YmMvDdBUetQKO1WBGWY1yLL2ySmAQE7uk8gh8ysL329zg1CrGPKcblm1kQEQ9W+vKfTVpakGKvuKCgGnnQxQYlp0sZ2z/RS5wZaWm/CrVlKbsZtGsL0=
before_install:
- sudo apt-get install pandoc
- git submodule update --init --recursive
install:
- pip install -r requirements.txt --use-mirrors
script:
- fab build
after_success: bash deploy.sh
notifications:
  email:
    on_success: always
    on_failure: always
